version: "3.7"

services:
  db:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "N@vislam1a"
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports: 
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@navislamia.com"
      PGADMIN_DEFAULT_PASSWORD: "N@vislam1a"
